### PR TITLE
Create Apple Developer and update Apple

### PR DESCRIPTION
**Pull request by Robot-DaneelOlivaw**
Create `apple-dev`. Update domains of iCloud and Apple News.

### CODE REVIEW

**Comment by EpLiar** [comment]
I have a HUGE pr on working: https://github.com/v2ray/domain-list-community/pull/647

So could you mark as draft before I finish?

**Comment by EpLiar** [comment]
Thank you, it will be finished on today

**Comment by EpLiar** [comment]
Now you can change this status. Thank you again.

**Comment by Robot-DaneelOlivaw** [comment]
This pull request is ready to be merged.

**Pull request merged**
