### PR TITLE
Create tld-!cn

### PR DESCRIPTION
**Pull request by EpLiar**
Reference: https://www.101domain.com/branded_domains.htm

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Remember to subtract the TLD here: http://xn--eqrt2g.xn--vuq861b/

**Comment by EpLiar** [comment]
> Remember to subtract the TLDs in here: http://xn--eqrt2g.xn--vuq861b/

What do you mean? I don't see any duplicate domains.

**Comment by Loyalsoldier** [comment]
Just to remind you.

**Comment by EpLiar** [comment]
@Loyalsoldier OK. I think it's time to update `tld-cn`.

**Comment by Loyalsoldier** [comment]
能在大陆备案的顶级域名，不意味着是中国大陆内使用的域名。

**Pull request merged**
