### PR TITLE
add some advertising domains

### PR DESCRIPTION
**Pull request by rhjdvsgsgks**

### CODE REVIEW

**Comment by kslr** [comment]
@Loyalsoldier request review

**Comment by Loyalsoldier** [comment]
@rhjdvsgsgks 

These are my opinions:
- I don't think `ironbeast.io` is part of `atom-data-ads`. It's more likely from `ironsrc.com`
- It's better to include sub domains of `supersonic.com` in `supersonic-ads` and `zynga.com` in `zynga-ads`, but okay in general.

**Comment by rhjdvsgsgks** [comment]
in my opinion general is better , website maintainer can add sub domain easily ,  but this domain list can't keep updating in time easily , general will contain whole domain so that any any new sub domain under this general domain will be matched easily

**Comment by Loyalsoldier** [comment]
> in my opinion general is better , website maintainer can add sub domain easily , but this domain list can't keep updating in time easily , general will contain whole domain so that any any new sub domain under this general domain will be matched easily

You misunderstand me. "in general" means "总体而言".

@kslr This PR is okay to be merged.

**Comment by rhjdvsgsgks** [comment]
it's my mistake ,  i misunderstand " in general " as " 'general' domain" ( a "general" string that can match all of the sub domain ) , apologize for my poor english

**Pull request merged**
