### PR TITLE
rearrange google and google-ads

### PR DESCRIPTION
**Pull request by forever8938**
Some google-ads domains are mixed in google, causing them not being included by category-ads.
I moved ad domains to google-ads. I also removed @ads arribute from those ad domains, because if all domains in a file has the same arribute, the arribute is not even necessary, right?

### CODE REVIEW

**Comment by kslr** [comment]
yes, https://github.com/v2ray/domain-list-community/blob/master/data/category-ads#L5

**Comment by OpportunityLiu** [comment]
图片
??

**Comment by forever8938** [comment]
> 图片
> ??

If this is a must I will add it back, but right now geosite:google-ads did the same thing.

**Comment by OpportunityLiu** [comment]
I'm not sure since I've never used the attributes, but the feature is shown in README.

**Comment by forever8938** [comment]
What I'm trying to show is that it's not necessary to use attribute to indicate ad domains, since we don't to mix them with normal domains in the same file. The same goes for other files like baidu-ads, but I didn't touch those.

**Comment by forever8938** [comment]
BTW I've confirmed that only files ending with "-ads" contains @ads attribute.

**Pull request merged**
