### PR TITLE
Scheduled update moved from azure pipelines to GitHub Actions

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Scheduled update for ookla-speedtest sub-list every 3 days.

### CODE REVIEW

**Comment by iochen** [comment]
Why **`schedule`**?

**Comment by iochen** [comment]
nothing about schedule showed in `azure-pipelines.yml`

**Comment by Loyalsoldier** [comment]
Automatically update ookla-speedtest by GitHub Actions if no more commits for too long.

**Comment by Loyalsoldier** [comment]
Azure-pipelines.yml will auto run every Wednesday.

**Comment by iochen** [comment]
Thank you, I didn't consider that before.

**Comment by iochen** [comment]
> Azure-pipelines.yml will auto run every Wednesday.

Won't it auto run about every 3 days?

**Pull request merged**
