### PR TITLE
Remove .cn domains

### PR DESCRIPTION
**Pull request by EpLiar**

### CODE REVIEW

**Comment by iochen** [comment]
The function of this repo is mainly to tag domains, route or further settings should be set by users.
Removing `.cn` domains may not be that proper, I think.

**Comment by EpLiar** [comment]
@iochen See https://github.com/v2ray/domain-list-community/pull/622 and https://github.com/Loyalsoldier/v2ray-rules-dat/issues/35

**Comment by Robot-DaneelOlivaw** [comment]
I don't understand either. If we're removing `.cn` from all sub-lists in `geolocation-!cn`, wouldn't it be faster to play with `tld-cn` in config file? It feels like we're drifting away from the purpose of this project.

**Comment by Loyalsoldier** [comment]
> I don't understand either. If we're removing `.cn` from all sub-lists in `geolocation-!cn`, wouldn't it be faster to play with `tld-cn` in config file? It feels like we're drifting away from the purpose of this project.

Oh, this idea is excellent, of which I don't think earlier.

**Comment by EpLiar** [comment]
Oh my weekend... 

Before this event, we should find a way to deal this rule.

**Comment by Loyalsoldier** [comment]
We can use this config to avoid `.cn` domains to be proxied if the default (fallback) outbound is proxy:

```
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "outboundTag": "Reject",
      "domain": [
        "geosite:category-ads-all"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Direct",
      "domain": [
        "geoip:tld-cn"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": [
        "geosite:geolocation-!cn"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Direct",
      "domain": [
        "geosite:cn"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Direct",
      "ip": [
        "geoip:cn",
        "geoip:private"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "network": "tcp,udp"
    }
  ]
}
```

Stupid me again.

**Comment by Robot-DaneelOlivaw** [comment]
> We can use this config to avoid .cn domains to be proxied if the default (fallback) outbound is proxy

Exactly! And for Apple and Microsoft, maybe we can have something like this:
```javascript
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },{
        "type": "field",
        "domain": ["geosite:apple", "geosite:microsoft"],
        "ip": ["geoip:cn", "geoip:hk", "geoip:mo", "geoip:tw", "geoip:jp", "geoip:sg"],
        "outboundTag": "direct"
      },{
        "type": "field",
        "domain": ["geosite:geolocation-!cn"],
        "outboundTag": "tls-outbound"
      },{
        "type": "field",
        "ip": ["geoip:cn", "geoip:private"],
        "outboundTag": "direct"
      }
    ]
  },
  
  "dns": {
    "servers": [
      "https://1.1.1.1/dns-query",
      {
        "address": "https+local://doh.pub/dns-query",
        "domains": [
          "geosite:cn",
          "geosite:apple",
          "geosite:microsoft"
        ]
      }
    ],
    "tag": "dns"
  }
```
It hands all domains of Apple and Microsoft to Chinese DNS, only takes direct outbound when a nearby IP is returned. Might help when some services have access points somewhere near China.

Anyway, glad things are simple now.

**Pull request merged**
