### PR TITLE
Update Steam

### PR DESCRIPTION
**Pull request by LamJH**
Update Steam Store domains, along with some CDNs used by Steam.

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Does the attr `@cdn` exist in V2Ray?

**Comment by iochen** [comment]
> Does the attr `@cdn` exist in V2Ray?

yes, and any attr can exist if you like.

**Comment by Loyalsoldier** [comment]
> yes, and any attr can exist if you like.

But how to use it in config file?

**Comment by iochen** [comment]
> > yes, and any attr can exist if you like.
> 
> But how to use it in config file?

https://github.com/v2ray/domain-list-community#attributes

**Pull request merged**
