### PR TITLE
Update Steam and geolocation-cn

### PR DESCRIPTION
**Pull request by LamJH**
Update and include CDNs of Steam in geolocation-cn. Please review if I'm doing it right.

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
This build failed: https://github.com/v2ray/domain-list-community/actions/runs/161821185

**Comment by EpLiar** [comment]
The generators probably need to be updated, or this syntax eliminated. Discussion needed.

**Comment by iochen** [comment]
> This build failed: https://github.com/v2ray/domain-list-community/actions/runs/161821185
> 
> It seems that it can NOT include sub-list's `attr` group of domains

It seems that it can not indeed, but even if it can, it should be `include:foo @bar`, there must be a space before `@`

**Comment by LamJH** [comment]
> It seems that it can not indeed, but even if it can, it should be `include:foo @bar`, there must be a space before `@`

Thanks for the fix. Sorry about the mess.

My intention was to sort out Steam CDNs with access point in China. People might not want their dozens gigabytes of games downloaded through proxy.

The only viable way now seems to be manually configuring in config file. Since if we create an alternative `steam-cdn` group just to include them into `geolocation-cn`, attribute will be pretty redundant.

**Pull request merged**
